### ISSUE TITLE
Bug: slither related workflows fail

### ISSUE THREAD

**Issue by shortdoom** [ConsenSysDiligence/napalm#7]
It seems that napalm workflows that depend on napalm-slither / slither fail to produce output. Manual slither execution works fine.

`napalm run detect` fail:

```
venv) user@nest:~/Github/Bugz/napalm$ napalm run detect /home/user/Github/Local/forgAi/core/engine/files/out/mainet:0xc21f107933612ecf5677894d45fc060767479a9b:AaveV2ERC4626/AaveV2ERC4626.sol
2024-03-04 21:51:20.027 | ERROR    | napalm_slither.slither_tool_runner:_run_analysis:47 - Error parsing slither output
Try running command locally:
slither --sarif - /home/user/Github/Local/forgAi/core/engine/files/out/mainet:0xc21f107933612ecf5677894d45fc060767479a9b:AaveV2ERC4626/AaveV2ERC4626.sol
Traceback (most recent call last):
  File "/home/user/Github/Bugz/napalm/venv/bin/napalm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/cli/base/run.py", line 78, in run
    results = run_tools(
              ^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/tool/run.py", line 75, in run_tools
    twins = _get_twins(storage)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/tool/run.py", line 29, in _get_twins
    detectors = pipe(
                ^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/toolz/functoolz.py", line 628, in pipe
    data = func(data)
           ^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/tool/run.py", line 33, in <lambda>
    map(lambda m: m.detectors),
                  ^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/package/collection.py", line 34, in detectors
    plugin_detectors = list(
                       ^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/napalm_slither/plugin.py", line 54, in detector_info
    return into_detector_info(slither_detector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/napalm_slither/detector_info.py", line 33, in into_detector_info
    return DetectorInfo(
           ^^^^^^^^^^^^^
TypeError: DetectorInfo.__init__() missing 1 required positional argument: 'confidence'
```

`napalm run direct` fail: 

```
(venv) user@nest:~/Github/Bugz/napalm$ napalm run direct /home/user/Github/Local/forgAi/core/engine/files/out/mainet:0xc21f107933612ecf5677894d45fc060767479a9b:AaveV2ERC4626/AaveV2ERC4
626.sol
2024-03-04 21:53:07.651 | ERROR    | napalm_slither.slither_tool_runner:_run_analysis:47 - Error parsing slither output
Try running command locally:
slither --sarif - --exclude abiencoderv2-array,arbitrary-send-erc20,arbitrary-send-erc20-permit,arbitrary-send-eth,array-by-reference,controlled-array-length,assembly,assert-state-change,backdoor,weak-prng,boolean-cst,boolean-equal,shadowing-builtin,cache-array-length,codex,constant-function-asm,constant-function-state,pragma,controlled-delegatecall,costly-loop,constable-states,immutable-states,cyclomatic-complexity,dead-code,delegatecall-loop,deprecated-standards,divide-before-multiply,domain-separator-collision,encode-packed-collision,enum-conversion,external-function,function-init-state,erc20-interface,erc721-interface,incorrect-exp,incorrect-return,solc-version,incorrect-equality,incorrect-unary,incorrect-using-for,shadowing-local,locked-ether,low-level-calls,mapping-deletion,events-access,events-maths,missing-inheritance,missing-zero-check,incorrect-modifier,msg-value-loop,calls-loop,multiple-constructors,name-reused,naming-convention,out-of-order-retryable,variable-scope,protected-vars,public-mappings-nested,redundant-statements,reentrancy-benign,reentrancy-eth,reentrancy-events,reentrancy-unlimited-gas,reentrancy-no-eth,return-bomb,return-leave,reused-constructor,rtlo,shadowing-abstract,incorrect-shift,similar-names,shadowing-state,storage-array,suicidal,tautological-compare,timestamp,too-many-digits,tx-origin,tautology,unchecked-lowlevel,unchecked-send,unchecked-transfer,unimplemented-functions,erc20-indexed,uninitialized-fptr-cst,uninitialized-local,uninitialized-state,uninitialized-storage,unprotected-upgrade,unused-return,unused-state,var-read-using-this,void-cst,write-after-write /home/user/Github/Local/forgAi/core/engine/files/out/mainet:0xc21f107933612ecf5677894d45fc060767479a9b:AaveV2ERC4626/AaveV2ERC4626.sol
Traceback (most recent call last):
  File "/home/user/Github/Bugz/napalm/venv/bin/napalm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/cli/base/run.py", line 78, in run
    results = run_tools(
              ^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/tool/run.py", line 75, in run_tools
    twins = _get_twins(storage)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/tool/run.py", line 29, in _get_twins
    detectors = pipe(
                ^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/toolz/functoolz.py", line 628, in pipe
    data = func(data)
           ^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/tool/run.py", line 33, in <lambda>
    map(lambda m: m.detectors),
                  ^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/package/collection.py", line 34, in detectors
    plugin_detectors = list(
                       ^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/napalm_slither/plugin.py", line 54, in detector_info
    return into_detector_info(slither_detector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/napalm_slither/detector_info.py", line 33, in into_detector_info
    return DetectorInfo(
           ^^^^^^^^^^^^^
TypeError: DetectorInfo.__init__() missing 1 required positional argument: 'confidence'
```

`napalm run inform` fail:

```
(venv) user@nest:~/Github/Bugz/napalm$ napalm run inform /home/user/Github/Local/forgAi/core/engine/files/out/mainet:0xc21f107933612ecf5677894d45fc060767479a9b:AaveV2
ERC4626/AaveV2ERC4626.sol
2024-03-04 22:18:26.765 | ERROR    | napalm_slither.slither_tool_runner:_run_analysis:47 - Error parsing slither output
Try running command locally:
slither --sarif - --exclude abiencoderv2-array,arbitrary-send-erc20,arbitrary-send-erc20-permit,arbitrary-send-eth,array-by-reference,controlled-array-length,assembly,assert-state-change,backdoor,weak-prng,boolean-cst,boolean-equal,shadowing-builtin,cache-array-length,codex,constant-function-asm,constant-function-state,pragma,controlled-delegatecall,costly-loop,constable-states,immutable-states,cyclomatic-complexity,dead-code,delegatecall-loop,deprecated-standards,divide-before-multiply,domain-separator-collision,encode-packed-collision,enum-conversion,external-function,function-init-state,erc20-interface,erc721-interface,incorrect-exp,incorrect-return,solc-version,incorrect-equality,incorrect-unary,incorrect-using-for,shadowing-local,locked-ether,low-level-calls,mapping-deletion,events-access,events-maths,missing-inheritance,missing-zero-check,incorrect-modifier,msg-value-loop,calls-loop,multiple-constructors,name-reused,naming-convention,out-of-order-retryable,variable-scope,protected-vars,public-mappings-nested,redundant-statements,reentrancy-benign,reentrancy-eth,reentrancy-events,reentrancy-unlimited-gas,reentrancy-no-eth,return-bomb,return-leave,reused-constructor,rtlo,shadowing-abstract,incorrect-shift,similar-names,shadowing-state,storage-array,suicidal,tautological-compare,timestamp,too-many-digits,tx-origin,tautology,unchecked-lowlevel,unchecked-send,unchecked-transfer,unimplemented-functions,erc20-indexed,uninitialized-fptr-cst,uninitialized-local,uninitialized-state,uninitialized-storage,unprotected-upgrade,unused-return,unused-state,var-read-using-this,void-cst,write-after-write /home/user/Github/Local/forgAi/core/engine/files/out/mainet:0xc21f107933612ecf5677894d45fc060767479a9b:AaveV2ERC4626/AaveV2ERC4626.sol
Traceback (most recent call last):
  File "/home/user/Github/Bugz/napalm/venv/bin/napalm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/cli/base/run.py", line 78, in run
    results = run_tools(
              ^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/tool/run.py", line 75, in run_tools
    twins = _get_twins(storage)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/tool/run.py", line 29, in _get_twins
    detectors = pipe(
                ^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/toolz/functoolz.py", line 628, in pipe
    data = func(data)
           ^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/tool/run.py", line 33, in <lambda>
    map(lambda m: m.detectors),
                  ^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/napalm/package/collection.py", line 34, in detectors
    plugin_detectors = list(
                       ^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/napalm_slither/plugin.py", line 54, in detector_info
    return into_detector_info(slither_detector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/napalm_slither/detector_info.py", line 33, in into_detector_info
    return DetectorInfo(
           ^^^^^^^^^^^^^
TypeError: DetectorInfo.__init__() missing 1 required positional argument: 'confidence'
```

**Comment by JoranHonig** [comment]
This is caused by me forgetting to release an update to the napalm-slither pkg, should work with 0.1.1

**Comment by shortdoom** [comment]
You need to bear with me now :)

Original errors are gone and now it successfully executes. However, there seems to be some issue with workflow storage for parsing slither output. Also, stdout seems to be empty even if napalm reports a successful scan (I often found slither's stdout quirky though). Notice "ERROR".

```
(venv) user@nest:~/Github/Bugz/napalm$ napalm run detect /home/user/Github/Local/forgAi/core/engine/files/out/mainet:0x29d2bcF0d70f95cE16697e645e
2B76d218d66109:OxODexPool/contracts/OxODexPool.sol
Slither output: 
2024-03-05 22:54:31.287 | ERROR    | napalm_slither.slither_tool_runner:_run_analysis:58 - Error parsing slither output
Try running command locally:
['slither', '--sarif', '-', '/home/user/Github/Local/forgAi/core/engine/files/out/mainet:0x29d2bcF0d70f95cE16697e645e2B76d218d66109:OxODexPool/contracts/OxODexPool.sol']
slither --sarif - /home/user/Github/Local/forgAi/core/engine/files/out/mainet:0x29d2bcF0d70f95cE16697e645e2B76d218d66109:OxODexPool/contracts/OxODexPool.sol
Ran 1 tools
Ran analysis using:     Semgrep OSS, with 3 rules
No issues found 0
```

Upon inspecting `result.stderr` from [napalm_slither.slither_tool_runner:_run_analysis:58](https://github.com/ConsenSysDiligence/napalm-slither/blob/86cff5b48e8cfe6a5a8a88eaa832477511ab5a97/napalm_slither/slither_tool_runner.py#L53) I get a little bit more info:

```
Slither error: 2024-03-05 22:58:15.992 | INFO     | napalm_slither.entry_point:napalm_entry_point_slither:18 - napalm_entry_point_slithers
2024-03-05 22:58:15.993 | DEBUG    | napalm.storage.workflow:_initialize_database:16 - Collection storage already initialised
```

I tried commenting out this early return in [napalm.storage.workflow:_initialize_database:16](https://github.com/ConsenSysDiligence/napalm/blob/fb8ec14f05c698ea1e844b0c4c12d8d333296753/napalm/storage/workflow.py#L17) so I get:

```
Slither error: 2024-03-05 23:01:42.850 | INFO     | napalm_slither.entry_point:napalm_entry_point_slither:18 - napalm_entry_point_slithers
2024-03-05 23:01:42.851 | DEBUG    | napalm.storage.workflow:_initialize_database:16 - Collection storage already initialised
2024-03-05 23:01:42.851 | DEBUG    | napalm.storage.workflow:_initialize_database:18 - Initialising meta collection storage
2024-03-05 23:01:42.863 | DEBUG    | napalm.storage.workflow:_initialize_database:28 - Successfully initialised meta collection storage
```

However, removing return doesn't repair error with parsing slither output. At the same time, napalm reports successful scan nevertheless.

I am not too familiar right now with how Storage is supposed to work so returning back to the Issue :)

edit:

`pip freeze`

```
napalm-core==0.1.2
napalm-slither==0.1.1
-e git+https://github.com/shortdoom/napalm.git@fb8ec14f05c698ea1e844b0c4c12d8d333296753#egg=napalm_toolbox
```

_my local branch is up to date with ConsenSysDiligence/napalm:main._

**Comment by JoranHonig** [comment]
Improving error reporting from downstream tools is wip 😄 

https://github.com/crytic/slither/issues/2337 would help improve things for slither specifically.


Doesn't look like storage is the issue to me, what happens when you run the slither command locally? Could be something like "your solc select isn't set up right".

**Comment by shortdoom** [comment]
Yes, you're right, that's `solc-select` issue. It would be good idea to surface this errors, yeah. 

What's worth mentioning is how `slither` actually resolves working directory. I ran `napalm` from external directory to the contracts themselves. For it to successfully run you need to run it from the contracts directory (where target .sol file is located) , best if there's a `slither.config.json` file present too if `solc_remaps` are used.

**Comment by shortdoom** [comment]
last comment and i think it's ok to close this issue

default workflows in `napalm workflows list` after installation of `napalm-core` are initially empty, it's required to first add individual collections to those workflows, otherwise they run empty (without applying rules). it's communicated in the output (0 rules run) but it's easy to miss as run is successful. on fresh build:

```
(venv-napalm) user@nest:~$ napalm workflow detect list
workflow detect contains:
(venv-napalm) user@nest:~$ napalm workflow direct list
workflow direct contains:
(venv-napalm) user@nest:~$ napalm workflow inform list
workflow inform contains:
(venv-napalm) user@nest:~$ napalm collections list
Installed collections:
  - slither/detectors
  - napalm-core/optimisations
  - napalm-core/detectors
  - napalm-core/indicators
 (venv-napalm) user@nest:~$ napalm run detect Contract.sol
Ran 1 tools
Ran analysis using:     Slither, with 0 rules
No issues found 0
(venv-napalm) user@nest:~$ napalm workflow detect add napalm-core/detectors
Successfully added collection napalm-core/detectors to workflow detect
```
 
i don't know if that's intended or not, but I think it could be added to docs, somewhere in [running-with-napalm.md](https://github.com/ConsenSysDiligence/napalm/blob/fb8ec14f05c698ea1e844b0c4c12d8d333296753/docs/running-with-napalm.md?plain=1#L38)

**Comment by JoranHonig** [comment]
Good point.

You should've had a prompt from the tool to automatically include the napalm-core collections in the default workflows. However, adding more useful information to the docs can't hurt 😅
